export const FETCHING_LOCATION_TYPES = 'FETCHING_LOCATION_TYPES'
export const FETCHING_LOCATION_TYPES_SUCCESS = 'FETCHING_LOCATION_TYPES_SUCCESS'
export const FETCHING_LOCATION_TYPES_FAILURE = 'FETCHING_LOCATION_TYPES_FAILURE'

export const FETCHING_LOCATIONS = 'FETCHING_LOCATIONS'
export const FETCHING_LOCATIONS_SUCCESS = 'FETCHING_LOCATIONS_SUCCESS'
export const FETCHING_LOCATIONS_FAILURE = 'FETCHING_LOCATIONS_FAILURE'
export const REFETCHING_LOCATIONS = 'REFETCHING_LOCATIONS'

export const UPDATE_QUERY = 'UPDATE_QUERY'
export const SET_LOCATION_ID = 'SET_LOCATION_ID' 

export const FETCHING_MACHINES = 'FETCHING_MACHINES'
export const FETCHING_MACHINES_SUCCESS = 'FETCHING_MACHINES_SUCCESS'
export const FETCHING_MACHINES_FAILURE = 'FETCHING_MACHINES_FAILURE'

export const FETCHING_LOCATION_TRACKING_ENABLED = 'FETCHING_LOCATION_TRACKING_ENABLED'
export const FETCHING_LOCATION_TRACKING_SUCCESS = 'FETCHING_LOCATION_TRACKING_SUCCESS'
export const FETCHING_LOCATION_TRACKING_FAILURE = 'FETCHING_LOCATION_TRACKING_FAILURE'

export const UPDATE_COORDINATES = 'UPDATE_COORDINATES'

export const SET_SELECTED_MACHINE = 'SET_SELECTED_MACHINE'
export const SET_SELECTED_LOCATION_TYPE = 'SET_SELECTED_LOCATION_TYPE'
export const SET_SELECTED_NUM_MACHINES = 'SET_SELECTED_NUM_MACHINES'

export const FETCHING_OPERATORS = 'FETCHING_OPERATORS'
export const FETCHING_OPERATORS_SUCCESS = 'FETCHING_OPERATORS_SUCCESS'
export const FETCHING_OPERATORS_FAILURE = 'FETCHING_OPERATORS_FAILURE'