export const FETCHING_LOCATION_TYPES = "FETCHING_LOCATION_TYPES";
export const FETCHING_LOCATION_TYPES_SUCCESS =
  "FETCHING_LOCATION_TYPES_SUCCESS";
export const FETCHING_LOCATION_TYPES_FAILURE =
  "FETCHING_LOCATION_TYPES_FAILURE";

export const FETCHING_LOCATIONS = "FETCHING_LOCATIONS";
export const FETCHING_LOCATIONS_SUCCESS = "FETCHING_LOCATIONS_SUCCESS";
export const FETCHING_LOCATIONS_FAILURE = "FETCHING_LOCATIONS_FAILURE";
export const SET_LOCATION_SERVICES_ENABLED = "SET_LOCATION_SERVICES_ENABLED";

export const FETCHING_LOCATION = "FETCHING_LOCATION";
export const FETCHING_LOCATION_SUCCESS = "FETCHING_LOCATION_SUCCESS";
export const FETCHING_LOCATION_FAILURE = "FETCHING_LOCATION_FAILURE";

export const LOCATION_DETAILS_CONFIRMED = "LOCATION_DETAILS_CONFIRMED";
//export const FAILED_LOCATION_DETAILS_CONFIRMATION = 'FAILED_LOCATION_DETAILS_CONFIRMATION'
export const CLOSE_CONFIRM_MODAL = "CLOSE_CONFIRM_MODAL";

export const FETCHING_MACHINES = "FETCHING_MACHINES";
export const FETCHING_MACHINES_SUCCESS = "FETCHING_MACHINES_SUCCESS";
export const FETCHING_MACHINES_FAILURE = "FETCHING_MACHINES_FAILURE";

export const FETCHING_LOCATION_TRACKING_ENABLED =
  "FETCHING_LOCATION_TRACKING_ENABLED";
export const FETCHING_LOCATION_TRACKING_SUCCESS =
  "FETCHING_LOCATION_TRACKING_SUCCESS";
export const FETCHING_LOCATION_TRACKING_FAILURE =
  "FETCHING_LOCATION_TRACKING_FAILURE";
export const INITIAL_FETCHING_LOCATION_TRACKING_FAILURE =
  "INITIAL_FETCHING_LOCATION_TRACKING_FAILURE";
export const HIDE_NO_LOCATION_TRACKING_MODAL =
  "HIDE_NO_LOCATION_TRACKING_MODAL";

export const UPDATE_BOUNDS = "UPDATE_BOUNDS";
export const UPDATE_IGNORE_MAX_ZOOM = "UPDATE_IGNORE_MAX_ZOOM";
export const SET_MAX_ZOOM = "SET_MAX_ZOOM";

export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const SET_MACHINE_FILTER = "SET_MACHINE_FILTER";
export const SET_NUM_MACHINES_FILTER = "SET_NUM_MACHINES_FILTER";
export const SET_VIEW_FAVORITE_LOCATIONS_FILTER =
  "SET_VIEW_FAVORITE_LOCATIONS_FILTER";
export const SET_LOCATION_TYPE_FILTER = "SET_LOCATION_TYPE_FILTER";
export const SET_OPERATOR_FILTER = "SET_OPERATOR_FILTER";
export const SET_MACHINE_VERSION_FILTER = "SET_MACHINE_VERSION_FILTER";

export const SET_SELECTED_ACTIVITY_FILTER = "SET_SELECTED_ACTIVITY_FILTER";
export const CLEAR_ACTIVITY_FILTER = "CLEAR_ACTIVITY_FILTER";

export const FETCHING_OPERATORS = "FETCHING_OPERATORS";
export const FETCHING_OPERATORS_SUCCESS = "FETCHING_OPERATORS_SUCCESS";
export const FETCHING_OPERATORS_FAILURE = "FETCHING_OPERATORS_FAILURE";

export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const LOGIN_LATER = "LOGIN_LATER";

export const SET_SELECTED_LMX = "SET_SELECTED_LMX";
export const MACHINE_CONDITION_UPDATED = "MACHINE_CONDITION_UPDATED";
export const MACHINE_CONDITION_REMOVED = "MACHINE_CONDITION_REMOVED";

export const MACHINE_SCORE_ADDED = "MACHINE_SCORE_ADDED";
export const LOCATION_MACHINE_REMOVED = "LOCATION_MACHINE_REMOVED";
export const IC_ENABLED_UPDATED = "IC_ENABLED_UPDATED";

export const ADDING_MACHINE_TO_LOCATION = "ADDING_MACHINE_TO_LOCATION";
export const MACHINE_ADDED_TO_LOCATION = "MACHINE_ADDED_TO_LOCATION";
export const MACHINE_ADDED_TO_LOCATION_FAILURE =
  "MACHINE_ADDED_TO_LOCATION_FAILURE";

export const ADD_MACHINE_TO_LIST = "ADD_MACHINE_TO_LIST";
export const REMOVE_MACHINE_FROM_LIST = "REMOVE_MACHINE_FROM_LIST";
export const CLEAR_SELECTED_STATE = "CLEAR_SELECTED_STATE";

export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const FETCHING_FAVORITE_LOCATIONS_SUCCESS =
  "FETCHING_FAVORITE_LOCATIONS_SUCCESS";
export const FAVORITE_LOCATION_ADDED = "FAVORITE_LOCATION_ADDED";
export const FAVORITE_LOCATION_REMOVED = "FAVORITE_LOCATION_REMOVED";
export const SELECT_FAVORITE_LOCATION_FILTER_BY =
  "SELECT_FAVORITE_LOCATION_FILTER_BY";
export const SELECT_LOCATION_LIST_FILTER_BY = "SELECT_LOCATION_LIST_FILTER_BY";

export const UPDATING_LOCATION_DETAILS = "UPDATING_LOCATION_DETAILS";
export const LOCATION_DETAILS_UPDATED = "LOCATION_DETAILS_UPDATED";
export const FAILED_LOCATION_DETAILS_UPDATE = "FAILED_LOCATION_DETAILS_UPDATE";

export const SUGGESTING_LOCATION = "SUGGESTING_LOCATION";
export const LOCATION_SUGGESTED = "LOCATION_SUGGESTED";
export const RESET_SUGGEST_LOCATION = "RESET_SUGGEST_LOCATION";

export const SUBMITTING_MESSAGE = "SUBMITTING_MESSAGE";
export const MESSAGE_SUBMITTED = "MESSAGE_SUBMITTED";
export const MESSAGE_SUBMISSION_FAILED = "MESSAGE_SUBMISSION_FAILED";

export const SET_SELECTED_OPERATOR = "SET_SELECTED_OPERATOR";
export const SET_SELECTED_LOCATION_TYPE = "SET_SELECTED_LOCATION_TYPE";

export const FETCHING_REGIONS = "FETCHING_REGIONS";
export const FETCHING_REGIONS_SUCCESS = "FETCHING_REGIONS_SUCCESS";
export const FETCHING_REGIONS_FAILURE = "FETCHING_REGIONS_FAILURE";

export const CLEAR_SEARCH_BAR_TEXT = "CLEAR_SEARCH_BAR_TEXT";
export const SET_SEARCH_BAR_TEXT = "SET_SEARCH_BAR_TEXT";

export const SET_UNIT_PREFERENCE = "SET_UNIT_PREFERENCE";

export const FETCHING_LOCATION_AND_MACHINE_COUNTS_SUCCESS =
  "FETCHING_LOCATION_AND_MACHINE_COUNTS_SUCCESS";

export const SET_SELECTED_MAP_LOCATION = "SET_SELECTED_MAP_LOCATION";
export const TRIGGER_UPDATE_BOUNDS = "TRIGGER_UPDATE_BOUNDS";
